config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :people
  resources :courses
  resources :rooms
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < Resource
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  has_and_belongs_to_many :resources
end

app/models/person.rb
class Person < Resource
end

app/models/resource.rb
# frozen_string_literal: true

class Resource < ApplicationRecord
  has_and_belongs_to_many :events
end

app/models/room.rb
class Room < Resource
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:name, :major, :year)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :language)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:name, :surname, :title, :email, :phone)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:number, :type, :capacity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/courses/_form.html.slim
= form_for @course do |f|
  - if @course.errors.any?
    #error_explanation
      h2 = "#{pluralize(@course.errors.count, "error")} prohibited this course from being saved:"
      ul
        - @course.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :major
    = f.text_field :major
  .field
    = f.label :year
    = f.text_field :year
  .actions = f.submit

app/views/courses/edit.html.slim
h1 Editing course

== render 'form'

=> link_to 'Show', @course
'|
=< link_to 'Back', courses_path

app/views/courses/index.html.slim
h1 Listing courses

table
  thead
    tr
      th Name
      th Major
      th Year
      th
      th
      th

  tbody
    - @courses.each do |course|
      tr
        td = course.name
        td = course.major
        td = course.year
        td = link_to 'Show', course
        td = link_to 'Edit', edit_course_path(course)
        td = link_to 'Destroy', course, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Course', new_course_path

app/views/courses/new.html.slim
h1 New course

== render 'form'

= link_to 'Back', courses_path

app/views/courses/show.html.slim
p#notice = notice

p
  strong Name:
  = @course.name
p
  strong Major:
  = @course.major
p
  strong Year:
  = @course.year

=> link_to 'Edit', edit_course_path(@course)
'|
=< link_to 'Back', courses_path

app/views/events/_form.html.slim
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      h2 = "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      ul
        - @event.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :language
    = f.text_field :language
  .actions = f.submit

app/views/events/edit.html.slim
h1 Editing event

== render 'form'

=> link_to 'Show', @event
'|
=< link_to 'Back', events_path

app/views/events/index.html.slim
h1 Listing events

table
  thead
    tr
      th Title
      th Language
      th
      th
      th

  tbody
    - @events.each do |event|
      tr
        td = event.title
        td = event.language
        td = link_to 'Show', event
        td = link_to 'Edit', edit_event_path(event)
        td = link_to 'Destroy', event, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Event', new_event_path

app/views/events/new.html.slim
h1 New event

== render 'form'

= link_to 'Back', events_path

app/views/events/show.html.slim
p#notice = notice

p
  strong Title:
  = @event.title
p
  strong Language:
  = @event.language

=> link_to 'Edit', edit_event_path(@event)
'|
=< link_to 'Back', events_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RuplaCore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.slim
= form_for @person do |f|
  - if @person.errors.any?
    #error_explanation
      h2 = "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
      ul
        - @person.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :surname
    = f.text_field :surname
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :phone
    = f.text_field :phone
  .actions = f.submit

app/views/people/edit.html.slim
h1 Editing person

== render 'form'

=> link_to 'Show', @person
'|
=< link_to 'Back', people_path

app/views/people/index.html.slim
h1 Listing people

table
  thead
    tr
      th Name
      th Surname
      th Title
      th Email
      th Phone
      th
      th
      th

  tbody
    - @people.each do |person|
      tr
        td = person.name
        td = person.surname
        td = person.title
        td = person.email
        td = person.phone
        td = link_to 'Show', person
        td = link_to 'Edit', edit_person_path(person)
        td = link_to 'Destroy', person, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Person', new_person_path

app/views/people/new.html.slim
h1 New person

== render 'form'

= link_to 'Back', people_path

app/views/people/show.html.slim
p#notice = notice

p
  strong Name:
  = @person.name
p
  strong Surname:
  = @person.surname
p
  strong Title:
  = @person.title
p
  strong Email:
  = @person.email
p
  strong Phone:
  = @person.phone

=> link_to 'Edit', edit_person_path(@person)
'|
=< link_to 'Back', people_path

app/views/rooms/_form.html.slim
= form_for @room do |f|
  - if @room.errors.any?
    #error_explanation
      h2 = "#{pluralize(@room.errors.count, "error")} prohibited this room from being saved:"
      ul
        - @room.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :number
    = f.text_field :number
  .field
    = f.label :type
    = f.text_field :type
  .field
    = f.label :capacity
    = f.text_field :capacity
  .actions = f.submit

app/views/rooms/edit.html.slim
h1 Editing room

== render 'form'

=> link_to 'Show', @room
'|
=< link_to 'Back', rooms_path

app/views/rooms/index.html.slim
h1 Listing rooms

table
  thead
    tr
      th Number
      th Type
      th Capacity
      th
      th
      th

  tbody
    - @rooms.each do |room|
      tr
        td = room.number
        td = room.type
        td = room.capacity
        td = link_to 'Show', room
        td = link_to 'Edit', edit_room_path(room)
        td = link_to 'Destroy', room, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Room', new_room_path

app/views/rooms/new.html.slim
h1 New room

== render 'form'

= link_to 'Back', rooms_path

app/views/rooms/show.html.slim
p#notice = notice

p
  strong Number:
  = @room.number
p
  strong Type:
  = @room.type
p
  strong Capacity:
  = @room.capacity

=> link_to 'Edit', edit_room_path(@room)
'|
=< link_to 'Back', rooms_path